<?php
/**
 * Generate vendor_prefixed/autoload.php from each prefixed package's composer.json.
 *
 * php-scoper rewrites `psr-4` namespace prefixes inside each package's
 * composer.json (e.g. `League\CommonMark\` becomes
 * `BlockFormatBridge\Vendor\League\CommonMark\`). This script walks every
 * package directory under vendor_prefixed/, reads the rewritten composer.json,
 * and emits a single autoload.php that registers a PSR-4 autoloader plus
 * loads any `files` entries.
 *
 * The output is intentionally minimal — no Composer\Autoload runtime, no
 * static class map. Just enough to make the prefixed packages loadable at
 * plugin runtime without depending on a top-level composer install inside
 * vendor_prefixed/.
 *
 * @package BlockFormatBridge
 */

declare(strict_types=1);

$root          = dirname( __DIR__ ) . '/vendor_prefixed';
$psr4_map      = array(); // prefix => array of relative dirs
$psr0_map      = array();
$files_to_load = array();
$classmap      = array();

if ( ! is_dir( $root ) ) {
	fwrite( STDERR, "vendor_prefixed/ does not exist; run php-scoper first.\n" );
	exit( 1 );
}

// Walk vendor_prefixed/{vendor}/{package}/composer.json.
foreach ( new DirectoryIterator( $root ) as $vendor_dir ) {
	if ( $vendor_dir->isDot() || ! $vendor_dir->isDir() ) {
		continue;
	}
	foreach ( new DirectoryIterator( $vendor_dir->getPathname() ) as $pkg_dir ) {
		if ( $pkg_dir->isDot() || ! $pkg_dir->isDir() ) {
			continue;
		}
		$composer = $pkg_dir->getPathname() . '/composer.json';
		if ( ! is_file( $composer ) ) {
			continue;
		}
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Build tool reads Composer metadata from local vendor packages.
		$data = json_decode( (string) file_get_contents( $composer ), true );
		if ( ! is_array( $data ) || empty( $data['autoload'] ) ) {
			continue;
		}
		$rel_pkg = $vendor_dir->getFilename() . '/' . $pkg_dir->getFilename();
		$auto    = $data['autoload'];

		if ( isset( $auto['psr-4'] ) && is_array( $auto['psr-4'] ) ) {
			foreach ( $auto['psr-4'] as $prefix => $paths ) {
				$paths = (array) $paths;
				foreach ( $paths as $p ) {
					$psr4_map[ $prefix ][] = $rel_pkg . '/' . trim( $p, '/' );
				}
			}
		}
		if ( isset( $auto['psr-0'] ) && is_array( $auto['psr-0'] ) ) {
			foreach ( $auto['psr-0'] as $prefix => $paths ) {
				$paths = (array) $paths;
				foreach ( $paths as $p ) {
					$psr0_map[ $prefix ][] = $rel_pkg . '/' . trim( $p, '/' );
				}
			}
		}
		if ( isset( $auto['files'] ) && is_array( $auto['files'] ) ) {
			foreach ( $auto['files'] as $f ) {
				$files_to_load[] = $rel_pkg . '/' . ltrim( $f, '/' );
			}
		}
		if ( isset( $auto['classmap'] ) && is_array( $auto['classmap'] ) ) {
			foreach ( $auto['classmap'] as $entry ) {
				$classmap[] = $rel_pkg . '/' . ltrim( $entry, '/' );
			}
		}
	}
}

$autoload  = "<?php\n";
$autoload .= "/**\n";
$autoload .= " * Auto-generated by tools/build-autoloader.php — do not edit by hand.\n";
$autoload .= " * Loads php-scoper'd dependencies for block-format-bridge.\n";
$autoload .= " */\n\n";
$autoload .= "if ( ! defined( 'ABSPATH' ) ) { /* allow CLI use too */ }\n\n";
$autoload .= '$bfb_prefixed_root = __DIR__;' . "\n\n";

// PSR-4
$autoload .= '$bfb_prefixed_psr4 = ' . var_export_pretty( $psr4_map ) . ";\n\n";
// PSR-0
$autoload .= '$bfb_prefixed_psr0 = ' . var_export_pretty( $psr0_map ) . ";\n\n";

$autoload .= <<<'PHP'
spl_autoload_register( function ( $class ) use ( $bfb_prefixed_root, $bfb_prefixed_psr4, $bfb_prefixed_psr0 ) {
	// PSR-4
	foreach ( $bfb_prefixed_psr4 as $prefix => $dirs ) {
		if ( $prefix !== '' && strpos( $class, $prefix ) !== 0 ) {
			continue;
		}
		$relative = substr( $class, strlen( $prefix ) );
		$relative = str_replace( '\\', '/', $relative ) . '.php';
		foreach ( $dirs as $dir ) {
			$candidate = $bfb_prefixed_root . '/' . $dir . '/' . $relative;
			if ( is_file( $candidate ) ) {
				require_once $candidate;
				return;
			}
		}
	}

	// PSR-0 (fallback for older packages, e.g. nette).
	foreach ( $bfb_prefixed_psr0 as $prefix => $dirs ) {
		if ( $prefix !== '' && strpos( $class, $prefix ) !== 0 ) {
			continue;
		}
		// PSR-0 underscore convention applies to the class portion only.
		$relative_namespace = '';
		$relative_class     = $class;
		if ( false !== ( $pos = strrpos( $class, '\\' ) ) ) {
			$relative_namespace = substr( $class, 0, $pos );
			$relative_class     = substr( $class, $pos + 1 );
		}
		$relative = str_replace( '\\', '/', $relative_namespace ) . '/' . str_replace( '_', '/', $relative_class ) . '.php';
		$relative = ltrim( $relative, '/' );
		foreach ( $dirs as $dir ) {
			$candidate = $bfb_prefixed_root . '/' . $dir . '/' . $relative;
			if ( is_file( $candidate ) ) {
				require_once $candidate;
				return;
			}
		}
	}
} );
PHP;
$autoload .= "\n\n";

// files: load eagerly
if ( ! empty( $files_to_load ) ) {
	$autoload .= "// Eagerly loaded files (composer 'files' autoload entries).\n";
	foreach ( $files_to_load as $f ) {
		$autoload .= 'require_once $bfb_prefixed_root . ' . var_export( '/' . $f, true ) . ";\n";
	}
}

// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents -- Build tool writes the generated local autoloader.
file_put_contents( $root . '/autoload.php', $autoload );
echo "Wrote $root/autoload.php\n";

/**
 * Pretty-printed var_export for arrays of strings.
 */
function var_export_pretty( array $data ): string {
	if ( empty( $data ) ) {
		return 'array()';
	}
	$out = "array(\n";
	foreach ( $data as $k => $v ) {
		if ( is_array( $v ) ) {
			$out .= "\t" . var_export( $k, true ) . " => array(\n";
			foreach ( $v as $vv ) {
				$out .= "\t\t" . var_export( $vv, true ) . ",\n";
			}
			$out .= "\t),\n";
		} else {
			$out .= "\t" . var_export( $k, true ) . ' => ' . var_export( $v, true ) . ",\n";
		}
	}
	$out .= ')';
	return $out;
}
